/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/3d/neptune.gltf") as any;
    return (
        <group {...props} dispose={null}>
            <group position={[0, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere005.geometry}
                //   material={materials.Neptune}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere005_1.geometry}
                //   material={materials["Atmosphere.005"]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/3d/neptune.gltf");