/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from 'three';

export default function Model(props) {
  const planetTexture = useTexture("/textures/saturn.png")
  const ringTexture = useTexture("/textures/saturn_rings.png")
 
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh>
          <sphereGeometry args={[5.5, 30, 30]} />
          <meshStandardMaterial map={planetTexture} />
        </mesh>
         <mesh key="rings" rotation={[Math.PI/1.8, 0, 0]}>
          <ringGeometry args={[8, 12, 50, 4]} />
          <meshStandardMaterial map={ringTexture} side={THREE.DoubleSide} />
        </mesh>
      </group>
    </group>
  );
}