/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* TODO:
  https://discourse.threejs.org/t/applying-a-texture-to-a-ringgeometry/9990
*/
import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from 'three';

export default function Model(props) {
  const planetTexture = useTexture("/textures/saturn.png")
  const ringTexture = useTexture("/textures/saturn_rings.png")
  const ringRef = useRef(null);
  const theta = 50;
  const phi = 4;
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh>
          <sphereGeometry args={[5.5, 30, 30]} />
          <meshStandardMaterial map={planetTexture} />
        </mesh>
        <mesh key="rings" rotation={[Math.PI / 1.8, 0, 0]}>
          <ringGeometry ref={ringRef} args={[8, 12, theta, phi]} />
          <meshStandardMaterial map={ringTexture} side={THREE.DoubleSide} transparent={true} />
        </mesh>
      </group>
    </group>
  );
}