/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from 'three';
import { Texture } from "three";
import Ring from "../Ring";

export default function Model(props) {
  const planetTexture = useTexture("/textures/saturn.png")

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh receiveShadow={true} castShadow={true}>
          <sphereGeometry args={[5.5, 30, 30]} />
          <meshStandardMaterial map={planetTexture} />
        </mesh>
        <group rotation={[Math.PI / 1.8, 0, 0]}>
          <Ring args={[8,12]} textureUrl={"/textures/saturn_rings.png"}/>
        </group>
      </group>
    </group>
  );
}

